#!/usr/bin/env bash
set -e

SCOPE="."
MAX_DEPTH=4

usage() {
  cat <<'EOF'
project_snapshot.sh - quick project snapshot for project-rebuild-tutor

Purpose:
  Scan a source-code project without reading large file contents, so Codex can build a rebuild-style learning roadmap.

Options:
  --scope PATH      Project or module path to scan. Default: .
  --max-depth N     Directory tree depth. Default: 4
  -h, --help        Show this help.

Output format:
  Markdown sections: scan scope, root files, important config files, source files, test files, and directory structure.

Common examples:
  ./project_snapshot.sh --scope .
  ./project_snapshot.sh --scope ./src --max-depth 3

Safety rules:
  Does not install dependencies.
  Does not modify files.
  Skips .git, node_modules, target, dist, build, vendor, .next, coverage.
  Does not read large file contents.
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --scope)
      SCOPE="${2:-.}"
      shift 2
      ;;
    --max-depth)
      MAX_DEPTH="${2:-4}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [ ! -d "$SCOPE" ]; then
  echo "Scope is not a directory: $SCOPE" >&2
  exit 1
fi

PRUNE_NAMES=".git node_modules target dist build vendor .next coverage"
find_pruned() {
  find "$SCOPE" \
    \( -name .git -o -name node_modules -o -name target -o -name dist -o -name build -o -name vendor -o -name .next -o -name coverage \) -prune -o "$@"
}

echo "# Project Snapshot"
echo
echo "- Scope: $SCOPE"
echo "- Note: generated by heuristic file scanning; no large file contents were read."
echo "- Skipped directories: $PRUNE_NAMES"
echo

echo "## Root Files"
find "$SCOPE" -maxdepth 1 -type f -print | sed 's#^\./##' | sort | head -100
echo

echo "## Important Config Files"
find_pruned -type f \( \
  -name 'package.json' -o -name 'pnpm-lock.yaml' -o -name 'yarn.lock' -o -name 'package-lock.json' -o \
  -name 'tsconfig*.json' -o -name 'vite.config.*' -o -name 'next.config.*' -o -name 'nuxt.config.*' -o \
  -name 'tauri.conf.json' -o -name 'Cargo.toml' -o -name 'pyproject.toml' -o -name 'requirements*.txt' -o \
  -name 'Dockerfile' -o -name 'docker-compose*.yml' -o -name '.github' -o -name '.eslintrc*' -o -name 'eslint.config.*' -o \
  -name 'prettier.config.*' -o -name '.prettierrc*' -o -name 'Makefile' -o -name 'CMakeLists.txt' \
\) -print | sort | head -200
echo

echo "## Source Files"
find_pruned -type f \( \
  -name '*.ts' -o -name '*.tsx' -o -name '*.js' -o -name '*.jsx' -o -name '*.vue' -o -name '*.svelte' -o \
  -name '*.py' -o -name '*.rs' -o -name '*.go' -o -name '*.java' -o -name '*.kt' -o -name '*.cs' -o \
  -name '*.cpp' -o -name '*.c' -o -name '*.h' -o -name '*.hpp' \
\) -print | sort | head -300
echo

echo "## Test Files"
find_pruned -type f \( \
  -name '*test*.*' -o -name '*spec*.*' -o -path '*/tests/*' -o -path '*/__tests__/*' \
\) -print | sort | head -200
echo

echo "## Directory Structure"
find "$SCOPE" -maxdepth "$MAX_DEPTH" \
  \( -name .git -o -name node_modules -o -name target -o -name dist -o -name build -o -name vendor -o -name .next -o -name coverage \) -prune -o \
  -type d -print | sort | head -300
